truecraft/blueprints/html.py
from flask import Blueprint, render_template, abort, request, redirect, session, url_for, send_file
from flask.ext.login import current_user, login_user, logout_user
from sqlalchemy import desc, or_, and_
from datetime import datetime, timedelta
from truecraft.objects import *
from truecraft.common import *
from truecraft.config import _cfg
from truecraft.email import send_confirmation, send_reset

import binascii
import os
import zipfile
import urllib
import re
import json
import locale
import shlex
import math

encoding = locale.getdefaultlocale()[1]
html = Blueprint('html', __name__, template_folder='../../templates')

@html.route("/")
def index():
    posts = BlogPost.query.order_by(desc(BlogPost.created)).limit(5)[:5]
    total = BlogPost.query.count()
    return render_template("index.html", posts=posts, total_pages=total // 5)

@html.route("/rss.xml")
def rss():
    posts = BlogPost.query.order_by(desc(BlogPost.created)).limit(10)[:10]
    return render_template("rss.xml", posts=posts)

@html.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        errors = dict()
        if not email:
            errors['email'] = 'Email is required.'
        else:
            if not re.match(r"^[^@]+@[^@]+\.[^@]+$", email):
                errors['email'] = 'Please use a valid email address.'
            if User.query.filter(User.username.ilike(username)).first():
                errors['username'] = 'This username is already in use.'
        if not username:
            errors['username'] = 'Username is required.'
        else:
            if not re.match(r"^[A-Za-z0-9_]+$", username):
                errors['username'] = 'Letters, numbers, underscores only.'
            if len(username) < 3 or len(username) > 24:
                errors['username'] = 'Must be between 3 and 24 characters.'
            if User.query.filter(User.username.ilike(username)).first():
                errors['username'] = 'This username is already in use.'
        if not password:
            errors['password'] = 'Password is required.'
        else:
            if len(password) < 5 or len(password) > 256:
                errors['password'] = 'Must be between 5 and 256 characters.'
        if errors != dict():
            return render_template("register.html", username=username, email=email, errors=errors)
        # All good, create an account for them
        user = User(username, email, password)
        user.confirmation = binascii.b2a_hex(os.urandom(20)).decode("utf-8")
        db.add(user)
        db.commit()
        send_confirmation(user)
        return redirect("/pending")

@html.route("/confirm/<confirmation>")
def confirm(confirmation):
    user = User.query.filter(User.confirmation == confirmation).first()
    if not user:
        return render_template("confirm.html", **{ 'success': False, 'user': user })
    else:
        user.confirmation = None
        login_user(user)
        db.commit()
        return render_template("confirm.html", **{ 'success': True, 'user': user })

@html.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if current_user:
            return redirect("/")
        reset = request.args.get('reset') == '1'
        return render_template("login.html", **{ 'return_to': request.args.get('return_to'), 'reset': reset })
    else:
        username = request.form['username']
        password = request.form['password']
        remember = request.form.get('remember-me')
        if remember == "on":
            remember = True
        else:
            remember = False
        user = User.query.filter(User.username.ilike(username)).first()
        if not user:
            return render_template("login.html", **{ "username": username, "errors": 'Your username or password is incorrect.' })
        if user.confirmation != '' and user.confirmation != None:
            return redirect("/pending")
        if not bcrypt.checkpw(password, user.password):
            return render_template("login.html", **{ "username": username, "errors": 'Your username or password is incorrect.' })
        login_user(user, remember=remember)
        if 'return_to' in request.form and request.form['return_to']:
            return redirect(urllib.parse.unquote(request.form.get('return_to')))
        return redirect("/")

@html.route("/logout")
@loginrequired
def logout():
    logout_user()
    return redirect("/")

@html.route("/forgot-password", methods=['GET', 'POST'])
def forgot_password():
    if request.method == 'GET':
        return render_template("forgot.html")
    else:
        email = request.form.get('email')
        if not email:
            return render_template("forgot.html", bad_email=True)
        user = User.query.filter(User.email == email).first()
        if not user:
            return render_template("forgot.html", bad_email=True, email=email)
        user.passwordReset = binascii.b2a_hex(os.urandom(20)).decode("utf-8")
        user.passwordResetExpiry = datetime.now() + timedelta(days=1)
        db.commit()
        send_reset(user)
        return render_template("forgot.html", success=True)

@html.route("/reset", methods=['GET', 'POST'])
@html.route("/reset/<username>/<confirmation>", methods=['GET', 'POST'])
def reset_password(username, confirmation):
    user = User.query.filter(User.username == username).first()
    if not user:
        redirect("/")
    if request.method == 'GET':
        if user.passwordResetExpiry == None or user.passwordResetExpiry < datetime.now():
            return render_template("reset.html", expired=True)
        if user.passwordReset != confirmation:
            redirect("/")
        return render_template("reset.html", username=username, confirmation=confirmation)
    else:
        if user.passwordResetExpiry == None or user.passwordResetExpiry < datetime.now():
            abort(401)
        if user.passwordReset != confirmation:
            abort(401)
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if not password or not password2:
            return render_template("reset.html", username=username, confirmation=confirmation, errors="Please fill out both fields.")
        if password != password2:
            return render_template("reset.html", username=username, confirmation=confirmation, errors="You seem to have mistyped one of these, please try again.")
        user.set_password(password)
        user.passwordReset = None
        user.passwordResetExpiry = None
        db.commit()
        return redirect("/login?reset=1")

@html.route("/pending")
def pending():
    return render_template("pending.html")

@html.route("/download")
def download():
    return render_template("download.html")

@html.route("/roadmap")
def roadmap():
    return render_template("roadmap.html")

@html.route("/blog/compose", methods=["GET", "POST"])
@adminrequired
def compose_blog():
    if request.method == 'GET':
        return render_template("compose.html")
    else:
        title = request.form.get('post-title')
        image_url = request.form.get('post-image')
        content = request.form.get('post-content')
        if not title or not image_url or not content:
            return render_template("compose.html", errors=True)
        post = BlogPost()
        post.author = current_user
        post.title = title
        post.image = image_url
        post.text = content
        db.add(post)
        db.commit()
        return redirect(url_for("html.view_blog", id=post.id, title=post.title))

@html.route("/blog/<int:id>/edit", methods=["GET", "POST"])
@adminrequired
def edit_blog(id):
    post = BlogPost.query.filter(BlogPost.id == id).first()
    if not post:
        abort(404)
    if request.method == "GET":
        return render_template("compose.html", post=post)
    else:
        title = request.form.get('post-title')
        image_url = request.form.get('post-image')
        content = request.form.get('post-content')
        if not title or not image_url or not content:
            return render_template("compose.html", errors=True)
        post.title = title
        post.image = image_url
        post.text = content
        db.commit()
        return redirect(url_for("html.view_blog", id=post.id, title=post.title))

@html.route("/blog/<int:id>/<path:title>")
def view_blog(id, title):
    post = BlogPost.query.filter(BlogPost.id == id).first()
    if not post:
        abort(404)
    return render_template("blog-post.html", post=post)

@html.route("/updates")
def updates():
    page = 1
    provided = request.args.get('page')
    if provided:
        try:
            page = int(provided)
        except:
            pass
    posts = BlogPost.query.order_by(desc(BlogPost.created)).offset((page - 1) * 5).limit(5)[:5]
    total = BlogPost.query.count()
    return render_template("updates.html", posts=posts, page=page, total_pages=total // 5)

@html.route("/u/<username>")
@html.route("/user/<username>")
def view_user(username):
    user = User.query.filter(User.username.ilike(username)).first()
    if not user:
        abort(404)
    return render_template("profile.html", profile=user)

templates/blog-post.html
{% extends "layout.html" %}
{% block title %}
<title>{{ post.title }} &mdash; TrueCraft</title>
{% endblock %}
{% block body %}
<h3>
    {{ post.title }}
    {% if user.admin %}
    <a href="{{ url_for("html.edit_blog", id=post.id) }}">Edit</a>
    {% endif %}
</h3>
<h4>Published {{ post.created.strftime("%b %d, %Y") }}</h4>
<img src="{{ post.image }}" />
{{ post.text | markdown }}
<div id="disqus_thread"></div>
<script type="text/javascript">
var disqus_shortname = 'truecraft';
(function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
{% endblock %}

templates/compose.html
{% extends "layout.html" %}
{% block body %}
<h3>Compose blog post</h3>
{% if errors %}
<div class="alert alert-danger">
    <p>All fields are required.</p>
</div>
{% endif %}
{% if post %}
<form action="{{ url_for("html.edit_blog", id=post.id) }}" method="POST">
{% else %}
<form action="/blog/compose" method="POST">
{% endif %}
    <div class="form-group">
        <label for="post-title">Title</label>
        <input type="text" name="post-title" id="post-title" class="form-control"
            value="{% if post %}{{ post.title }}{% endif %}" />
    </div>
    <div class="form-group">
        <label for="post-image">Image URL</label>
        <input type="text" name="post-image" id="post-image" class="form-control" 
            value="{% if post %}{{ post.image }}{% endif %}" />
    </div>
    <div class="form-group">
        <label for="post-content">Content</label>
        <textarea name="post-content" id="post-content" rows="20"
            class="form-control">{% if post %}{{ post.text }}{% endif %}</textarea>
    </div>
    <button type="submit" class="btn btn-success btn-block">Publish</button>
</form>
{% endblock %}
{% block scripts %}
<script>
(function() {
    var editor = new Editor();
    editor.render();
})();
</script>
{% endblock %}

templates/confirm.html
{% extends "layout.html" %}
{% block body %}
<h3>Registration complete</h3>
<p>Maybe now you want to <a href="/download">download</a> TrueCraft?</p>
{% endblock %}

templates/forgot.html
{% extends "layout.html" %}
{% block body %}
<div class="text-center">
    <h2>Reset password</h2>
</div>
<hr />
{% if success %}
<p>We've sent you an email with further instructions. It should arrive soon. <a href="mailto:support@kerbalstuff.com">Email us</a>
if you run into trouble.</p>
{% else %}
<div class="row">
    <form class="form-horizontal col-md-6" role="form" action="/forgot-password" method="POST">
        {% if bad_email %}
        <p>Double check your email address, we don't recognize you.</p>
        {% endif %}
        <div class="form-group">
            <label for="email" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="email" placeholder="Email" name="email" value="{{ email }}">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </div>
    </form>
    <div class="col-md-6">
        {% if errors %}
        <p class="text-danger">{{ errors }}</p>
        {% endif %}
    </div>
</div>
{% endif %}
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block body %} 
{% filter markdown %}

# TrueCraft

The good old days of Minecraft, brought back in all their simplistic glory.

## About TrueCraft

A completely [clean-room](https://en.wikipedia.org/wiki/Clean_room_design)
implementation of Minecraft beta 1.7.3 (circa September 2011). No decompiled
code has been used in the development of this software.

I miss the old days of Minecraft, when it was a simple game. It was nearly
perfect. Most of what Mojang has added since beta 1.7.3 is fluff, life support
for a game that was "done" years ago. This is my attempt to get back to the
original spirit of Minecraft, before there were things like the End, or
all-in-one redstone devices, or village gift shops. A simple sandbox where you
can build and explore and fight with your friends. I miss that.

[**Roadmap »**](/roadmap)

<a class="rss" href="/rss.xml"><img src="/static/rss.png" /></a>

# Updates

Some of these screenshots are of the official Minecraft client connecting to a
TrueCraft server, and some are of the TrueCraft client connecting to a TrueCraft
server. You can tell the difference by the texture packs - the official assets
are screenshots of the official Minecraft client.

{% endfilter %}

{% for post in posts %}
<h3>
    <a href="{{ url_for("html.view_blog", id=post.id, title=post.title) }}">{{ post.title }}</a>
    <small>{{ post.created.strftime("%b %d, %Y") }}</small>
</h3>
<img src="{{ post.image }}" />
<p>{{ post.text | firstparagraph | markdown }} <a href="{{ url_for("html.view_blog", id=post.id, title=post.title) }}">Read more »</a></p>
{% endfor %}

{% if user.admin %}
<a href="/blog/compose">Compose new post</a>
{% endif %}

<div class="text-center">
    <ul class="pagination">
        {% for i in range(1, total_pages + 2) %}
            {% if i == 1 %}
            <li class="active"><a href="/updates?page={{ i }}">{{ i }}</a></li>
            {% else %}
            <li><a href="/updates?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        <li>
            <a href="/updates?page=2" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block title %}
        <title>TrueCraft</title>
        {% endblock %}
        <link rel="stylesheet" href="//cdn.jsdelivr.net/editor/0.1.0/editor.css"> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">    
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
        <link rel="alternate" type="application/rss+xml" title="TrueCraft Updates" href="/rss.xml">
        <link rel="icon" type="image/vnd.microsoft.icon" href="//avatars2.githubusercontent.com/u/4286195?v=2&s=200">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link rel="stylesheet" href="/static/base.css">
        {% block styles %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <header>
                <h1 class="title">
                    <a href="/">TrueCraft</a>
                </h1>
            </header>
            <div class="content">
                <p class="tagline">A free and open-source implementation of Minecraft Beta 1.7.3</p>
                <div class="main">
                    <nav class="navbar">
                        <div class="inner">
                            <ul class="nav navbar-nav">
                                <li><a href="/download">Download</a></li>
                                <li><a href="/updates">Updates</a></li>
                                <li><a href="https://github.com/SirCmpwn/TrueCraft">Github</a></li>
                                <li><a href="https://reddit.com/r/truecraft">Community</a></li>
                                <li><a href="http://webchat.esper.net/?nick=&channels=truecraft">Chat</a></li>
                            </ul>
                            <div class="collapse navbar-collapse" id="navbar-collapse">
                                {% if not user %}
                                <ul class="nav navbar-nav navbar-right">
                                    <li><a href="/login">Log In</a></li>
                                    <li><a href="/register">Register</a></li>
                                </ul>
                                {% else %}
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="navbar-text">Hi <a href="/user/{{ user.username }}">{{ user.username }}</a> &mdash; <a href="/logout">Log out</a></li>
                                </ul>
                                {% endif %}
                            </div>
                            <span class="blc"></span>
                            <span class="trc"></span>
                        </div>
                    </nav>
                    <article class="body">
                        {% block body %}{% endblock %}
                    </article>
                </div>
            </div>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="//cdn.jsdelivr.net/editor/0.1.0/editor.js"></script>
        <script src="//cdn.jsdelivr.net/editor/0.1.0/marked.js"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block body %}
<h3>Log In</h3>
<div class="container">
    <div class="row">
        {% if reset %}
        <p>Your password has been reset. You can now log in.</p>
        {% endif %}
        <form class="form-horizontal col-md-8" role="form" action="/login" method="POST">
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="username" placeholder="Username" name="username" value="{{ username }}">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" placeholder="Password" name="password">
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label class="col-sm-10 col-sm-offset-2">
                        <input type="checkbox" name="remember-me" id="remember-me">
                        Remember Me
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <input type="submit" value="Log In" class="btn btn-primary">
                </div>
            </div>
            {% if return_to %}
            <input type="hidden" name="return_to" value="{{ return_to }}">
            {% endif %}
        </form>
        <div class="col-md-4">
            {% if errors %}
            <p class="text-danger">{{ errors }}</p>
            {% endif %}
            <a href="/forgot-password">Reset Password</a>
        </div>
    </div>
</div>
{% endblock %}

templates/not_found.html
{% extends "layout.html" %}
{% block body %}
404 Not Found
{% endblock %}

templates/pending.html
{% extends "layout.html" %}
{% block body %}
<h2>Check your email</h2>
<p>You'll soon receive an email to confirm your account.</p>
{% endblock %}

templates/profile.html
{% extends "layout.html" %}
{% block body %}
<h3>{{ profile.username }}</h3>
<div class="row">
    <div class="col-md-4">
        <img src="https://placehold.it/250x400" />
    </div>
    <div class="col-md-8">
        <p>Joined {{ profile.created.strftime("%b %d, %Y ") }}</p>
        <p>TODO: Anything else of interest on these pages</p>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends "layout.html" %}
{% block body %}
<h2>Register an Account</h2>
<p>Registering for an account will allow you to play on authenticated servers.</p>
<div class="row">
    <form role="form" method="POST" action="/register" class="col-md-8">
        <div class="form-group {% if 'email' in errors %}has-error{% endif %}">
            <label for="email"> Email Address
            {% if 'email' in errors %}
            &mdash; <span class="text-danger">{{ errors['email'] }}</span>
            {% endif %}
            </label>
            <input type="email" class="form-control" id="email" name="email" placeholder="john@example.com" value="{{ email }}">
        </div>
        <div class="form-group {% if 'username' in errors %}has-error{% endif %}">
            <label for="username">Username
            {% if 'username' in errors %}
            &mdash; <span class="text-danger">{{ errors['username'] }}</span>
            {% endif %}
            </label>
            <input type="text" class="form-control" id="username" name="username" placeholder="john" value="{{ username }}">
        </div>
        <div class="form-group {% if 'password' in errors %}has-error{% endif %}">
            <label for="password">Password
            {% if 'password' in errors %}
            &mdash; <span class="text-danger">{{ errors['password'] }}</span>
            {% endif %}
            </label>
            <input type="password" class="form-control" id="password" name="password" placeholder="hunter2">
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-8">
                <input type="submit" value="Register" class="btn btn-default btn-block">
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/reset.html
{% extends "layout.html" %}
{% block body %}
<div class="text-center">
    <h2>Reset password</h2>
</div>
<hr />
{% if expired %}
<p>This link has expired. Please <a href="/forgot-password">re-apply</a> for a password reset.</p>
{% else %}
<div class="row">
    <form role="form" action="/reset/{{ username }}/{{ confirmation }}" method="POST">
        <div class="form-group">
            <label for="password">New Password</label>
            <input type="password" class="form-control" id="password" placeholder="Password" name="password">
        </div>
        <div class="form-group">
            <label for="password2">New Password (again)</label>
            <input type="password" class="form-control" id="password2" placeholder="...again" name="password2">
        </div>
        <div class="form-group">
            <input type="submit" value="Submit" class="btn btn-primary">
        </div>
    </form>
    <div class="col-md-6">
        {% if errors %}
        <p class="text-danger">{{ errors }}</p>
        {% endif %}
    </div>
</div>
{% endif %}
{% endblock %}

templates/roadmap.html
{% extends "layout.html" %}

{% macro feature(name, progress="not-started", indent=False, comments=None) -%}
<tr {% if comments %}title="{{ comments }}"{% endif %}>
    {% if indent %}
    <td style="padding-left: 50px;">
    {% else %}
    <td>
    {% endif %}
        {{ name }}
    </td>
    {% if progress == "done" %}
    <td class="success">Complete</td>
    {% elif progress == "in-progress" %}
    <td class="warning">In progress</td>
    {% elif progress == "meta" %}
    <td></td>
    {% else %}
    <td class="danger">Not started</td>
    {% endif %}
</tr>

{%- endmacro %}

{% block body %}
<p>Some features that are in-progress will give more details when hovered over.</p>

<h1>Server</h1>

<table class="table">
    <thead>
        <tr>
            <th>Feature</th>
            <th>Progress</th>
        </tr>
    </thead>
    <tbody>
        {{ feature("Beta 1.7.3 networking", "done") }}
        {{ feature("MCRegion worlds", "done") }}
            {{ feature("Tile entities", "done", indent=True) }}
            {{ feature("Multiworld", "not-started", indent=True) }}
            {{ feature("Player metadata", "done", indent=True) }}
        {{ feature("Entities", "meta") }}
            {{ feature("Physics", "done", indent=True) }}
            {{ feature("Item entities", "done", indent=True) }}
            {{ feature("Falling blocks", "done", indent=True) }}
            {{ feature("Players", "done", indent=True) }}
            {{ feature("Mobs", "in-progress", indent=True) }}
            {{ feature("Minecarts", "not-started", indent=True) }}
            {{ feature("Boats", "not-started", indent=True) }}
        {{ feature("AI", "meta") }}
            {{ feature("Peaceful", "in-progress", indent=True) }}
            {{ feature("Hostile", "not-started", indent=True) }}
            {{ feature("Special", "not-started", indent=True) }}
        {{ feature("Terrain generation", "done") }}
            {{ feature("Perlin base terrain", "done", indent=True) }}
            {{ feature("Biomes", "done", indent=True) }}
            {{ feature("Caves", "done", indent=True) }}
            {{ feature("Decorators", "done", indent=True) }}
        {{ feature("Window management", "meta") }}
            {{ feature("Inventory", "done", indent=True) }}
            {{ feature("Crafting", "done", indent=True) }}
            {{ feature("Furnaces", "not-started", indent=True) }}
            {{ feature("Chests", "done", indent=True) }}
        {{ feature("Modding API", "not-started") }}
        {{ feature("Game logic", "meta") }}
            {{ feature("Farming", "in-progress", indent=True, comments="Wheat and sugarcane are done") }}
            {{ feature("Doors", "done", indent=True) }}
            {{ feature("Unusual item drops", "done", indent=True) }}
            {{ feature("Block updates", "done", indent=True) }}
            {{ feature("Fluid simulation", "done", indent=True) }}
            {{ feature("Portals", "not-started", indent=True) }}
            {{ feature("Signs", "done", indent=True) }}
            {{ feature("Trees", "in-progress", indent=True, comments="Generation is done but not hooked up to saplings") }}
            {{ feature("TNT", "not-started", indent=True) }}
            {{ feature("Redstone", "not-started", indent=True) }}
            {{ feature("Bonemeal", "not-started", indent=True) }}
            {{ feature("Fishing", "not-started", indent=True) }}
            {{ feature("Fire", "not-started", indent=True) }}
            {{ feature("Jukeboxes", "not-started", indent=True) }}
            {{ feature("Beds", "in-progress", indent=True, comments="Placement is done, sleeping is not") }}
            {{ feature("Directional blocks", "done", indent=True) }}
        {{ feature("Lighting", "done") }}
        {{ feature("Weather", "not-started") }}
        {{ feature("Combat", "not-started") }}
        {{ feature("Food", "not-started") }}
    </tbody>
</table>

<h1>Client</h1>

<table class="table">
    <thead>
        <tr>
            <th>Feature</th>
            <th>Progress</th>
        </tr>
    </thead>
    <tbody>
        {{ feature("Launcher", "in-progress") }}
        {{ feature("Beta 1.7.3 networking", "done") }}
        {{ feature("World decoding", "done") }}
        {{ feature("Chat", "done") }}
        {{ feature("Window management", "not-started") }}
        {{ feature("World interaction", "not-started") }}
        {{ feature("Combat", "not-started") }}
        {{ feature("Particles", "not-started") }}
        {{ feature("Input", "meta") }}
            {{ feature("Movement and look", "done", indent=True) }}
            {{ feature("Custom key bindings", "not-started", indent=True) }}
        {{ feature("Rendering terrain", "meta") }}
            {{ feature("Basic support", "done", indent=True) }}
            {{ feature("Blocks w/special textures", "in-progress", indent=True) }}
            {{ feature("Blocks w/special models", "in-progress", indent=True) }}
        {{ feature("Rendering entities", "meta") }}
            {{ feature("Players", "not-started", indent=True) }}
            {{ feature("Item entities", "not-started", indent=True) }}
            {{ feature("Falling blocks", "not-started", indent=True) }}
            {{ feature("Mobs", "not-started", indent=True) }}
            {{ feature("Minecarts", "not-started", indent=True) }}
            {{ feature("Boats", "not-started", indent=True) }}
    </tbody>
</table>

<h1>Auth Servers</h1>

<table class="table">
    <thead>
        <tr>
            <th>Feature</th>
            <th>Progress</th>
        </tr>
    </thead>
    <tbody>
        {{ feature("Website", "done") }}
            {{ feature("User registration", "done", indent=True) }}
            {{ feature("Content", "done", indent=True) }}
            {{ feature("Updates feed", "done", indent=True) }}
        {{ feature("Authentication API", "done") }}
        {{ feature("Skins", "not-started") }}
        {{ feature("Capes", "not-started") }}
    </tbody>
</table>

{% endblock %}

templates/updates.html
{% extends "layout.html" %}
{% block body %} 
<a class="rss" href="/rss.xml"><img src="/static/rss.png" /></a>
<h2>TrueCraft Updates</h2>

{% for post in posts %}
<h3>
    <a href="{{ url_for("html.view_blog", id=post.id, title=post.title) }}">{{ post.title }}</a>
    <small>{{ post.created.strftime("%b %d, %Y") }}</small>
</h3>
<img src="{{ post.image }}" />
<p>{{ post.text | firstparagraph | markdown }} <a href="{{ url_for("html.view_blog", id=post.id, title=post.title) }}">Read more »</a></p>
{% endfor %}

<div class="text-center">
    <ul class="pagination">
        {% if page != 1 %}
        <li>
            <a href="/updates?page={{ page - 1 }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}
        {% for i in range(1, total_pages + 2) %}
            {% if i == page %}
            <li class="active"><a href="/updates?page={{ i }}">{{ i }}</a></li>
            {% else %}
            <li><a href="/updates?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page != total_pages %}
        <li>
            <a href="/updates?page={{ page + 1 }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}